### ISSUE TITLE
Command `wab delete` does not work.

### ISSUE THREAD

**Issue by CorruptComputer** [TheBugYouCantFix/wiki-reddit-bot#2]
Command `wab delete` does not work.

See here: https://www.reddit.com/r/PleX/comments/unza3w/plex_web_v4811_released/i8d7d1z/?context=3

Got the `wab delete` command from the link that the bot posted in the footer of its message: https://www.reddit.com/r/wikipedia_answer_bot/comments/q79g2t/delete_feature_added/

**Comment by TheBugYouCantFix** [comment]
I suppose you've written the comment when the bot's response hadn't yet gotten more than 2 downvotes. Otherwise, the redditt API(praw) might've just not updated the number of downvotes if you left your command right after leaving a downvote. Generally, this command works fine and has been tested before so that shouldn't be any significant issue.

**Comment by CorruptComputer** [comment]
The karma for that comment was in the double digit negative when I commented that. It's at -33 now, but iirc at the time it was around -20.

**Comment by TheBugYouCantFix** [comment]
It doesn't depend on the current karma value anyways. So, if it actually was at -20 at that moment, I barely have a clue. Maybe that was some bug with reddit API, hosting or anything else
